### PR TITLE
Add nulls & inf to hypothesis test for DataFrame.join

### PR DESCRIPTION
**Pull request by DeaMariaLeon**
Feedback welcome.

### CODE REVIEW

**Comment by DeaMariaLeon** [comment]
Infinity is not included on what we previously had, because there are the min and max values. https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.floats

I'll get back to you for the rest. :)

**Comment by MarcoGorelli** [comment]
ah thanks for explaining - maybe we could amend the previous example to have just
```
st.floats()
```
then? as far as I understood, the reason for the `min_value` and `max_value` where because of UInt64, but floats are fine?

**Comment by DeaMariaLeon** [comment]
There had been an error also with the Floats64 too, so I added the max/min values for those as well.
But I checked and it seems to be working. 🤔

Ok, so I'll set them to`st.floats()`.

**Comment by MarcoGorelli** [comment]
>  I checked and it seems to be working

love it when things "fix themselves" 😄

**Review by MarcoGorelli — APPROVED** [review]

**Pull request merged**
